export const Price = 'Precio'
export const Quantity = 'Cantidad'
export const EmptyCart = 'Tu carrito esta vacío'
export const Subtotal = 'Subtotal'
export const Total = 'Total'
export const YouCart = 'Tu Carrito'
export const DelCart = 'Vaciar Carrito'