export const Mark = 'Marca'
export const Year = 'Año'
export const Version = 'Versión'
export const Stock = 'Disponibles'
export const Description = 'Descripción'
export const GoToCart = 'Ir al Carrito'
export const Currency = 'USD'
export const CurrencyARS = 'ARS'